title: Ceylon
interpolate: true

haml|html:
  :format: :xhtml

profiles:
  development:
    disqus_developer: true
    dev: true
  production:
    base_url: http://ceylon-lang.org/
google_analytics: UA-24748553-1
google_analytics_domain: ceylon-lang.org
disqus: ceylonlang
